### ISSUE TITLE
should we add Add type definition to client?

### ISSUE THREAD

**Issue by cyberhck** [crazyfactory/tinka#152]
instead of
https://github.com/crazyfactory/tinka/blob/f684a95ae66d9eb79f49e2a2cc306949b9442a7f/src/Client.ts#L7
should we do:
```typescript
export class Client extends Stack<IN=IFetchRequest, OUT=IFetchResponse> { 
```

**Comment by paibamboo** [comment]
LGTM

**Comment by wmathes** [comment]
it was like that in the early beginning. We (Nish and I) changed that, because when an object is passed down through the stack, the object can change its type. Values can be added or removed etc. 

One example for this was the CacheMW and the AuthMW will probably do the same. So not to impose a fixed type on all steps the generic type was replaced with any.

**Comment by paibamboo** [comment]
I was thinking about that too. But I thought since they were middlewares, they should get and return the same type. For example CacheMiddleware also gets `IFetchRequest` and returns `Promise<IFetchResponse<any>>`. This is not the case?

**Comment by paibamboo** [comment]
Closing as #154 was closed (without merged)
